server:
  port: 8068
  servlet:
    context-path: /talent
  tomcat:
    uri-encoding: UTF-8
web:
  upload-path: c:/talent/

source:
  photo:
    url: http://app.cjwsjy.com.cn/UploadedFiles/Framework.Web/

logging:
  level:
    root: info
  file: c:/talent/logs/talent.log

spring:
  profiles:
    active: dev
#    active: prod
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  resources:
    static-locations: file:${web.upload-path}
  datasource:
#    username: bqdw
#    password: cjwsjy.nchr
#    url: jdbc:sqlserver://10.6.191.38:1433;DatabaseName=BQDW
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.6.191.38:1433;DatabaseName=BQDW
    username: bqdw
    password: cjwsjy.nchr
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 500
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM hr_dm_num_cube
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
      filter:
        stat:
        # 慢SQL记录
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.cjwsjy.talents.entity
  configuration:
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    cache-enabled: true
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      db-type: SQL_SERVER
      capital-mode: false #开启大写命名
      column-like: true #开启 LIKE 查询